# Generated by Django 5.0.2 on 2024-02-25 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('middel_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('userID', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('photo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ID_card_type', models.CharField(blank=True, choices=[('National ID', 'National ID'), ('Voters ID', 'Voters ID'), ('Passport ID', 'Passport ID')], default='', max_length=100, null=True)),
                ('ID_card_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ID_photo_front', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ID_photo_back', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('otp', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('businessName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('natureOfBusiness', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('businessType', models.CharField(blank=True, choices=[('Buness type 1', 'Business type 1'), ('Buness type 2', 'Business type 2'), ('Buness type 3', 'Business type 3')], default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('businessLogo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Ghana', max_length=100, null=True)),
                ('regionState', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('town', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ceo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('role', models.CharField(blank=True, default='superuser', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
