# Generated by Django 5.0.2 on 2024-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='middel_name',
            new_name='middle_name',
        ),
    ]
