# Generated by Django 5.0.2 on 2024-02-19 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usermodel_id_card_number_usermodel_id_card_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('businessName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('natureOfBusiness', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('businessType', models.CharField(blank=True, choices=[('Buness type 1', 'Business type 1'), ('Buness type 2', 'Business type 2'), ('Buness type 3', 'Business type 3')], default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('businessLogo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Ghana', max_length=100, null=True)),
                ('regionState', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('town', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
