# Generated by Django 5.0.2 on 2024-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_middel_name_usermodel_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, default='False', max_length=20, null=True),
        ),
    ]
