# Generated by Django 5.0.2 on 2024-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usermodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, default='Null', max_length=20, null=True),
        ),
    ]
